import { Router } from 'express';
import { generateCode, getMyCodes, validateCode, getAllCodes, getHistory, getAllHistory, getEmployeePerformance, toggleCodeStatus } from '../controllers/referral';
import { authorize } from '../common/guards/role.guard';

const router = Router();

// Public: Validate code during checkout
router.post('/validate', validateCode);

// Protected: Super Admin, Admin, or Employee generating their code
router.post('/generate', authorize(['super_admin', 'admin', 'employee']), generateCode);

// Protected: Get all codes generated by the requesting employee
router.get('/my-codes', authorize(['super_admin', 'admin', 'employee']), getMyCodes);

// Protected: Get all codes from ALL users (Master View)
router.get('/all-codes', authorize(['super_admin', 'admin']), getAllCodes);

// Protected: Get commission history for the requesting employee
router.get('/history', authorize(['super_admin', 'admin', 'employee']), getHistory);

// Protected: Get global commission history for ALL employees
router.get('/all-history', authorize(['super_admin', 'admin']), getAllHistory);

// Protected: Get specific employee performance
router.get('/performance/:employeeId', authorize(['super_admin', 'admin']), getEmployeePerformance);

// Protected: Toggle code status
router.patch('/:codeId/toggle-status', authorize(['super_admin', 'admin', 'employee']), toggleCodeStatus);

export default router;
